### ISSUE TITLE
Print of Integer leads to core dump

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/heads_ide#20]
Using the internal "print" in ThingML map anything directly to the target print function
Generated code made is similar to:
    int  myVar;
    fprintf(stdout, myVar);
This should lead to a compilation error not to core dump

**Comment by brice-morin** [comment]
Related to issue #23

**Comment by brice-morin** [comment]
@Lyadis I have implemented some helper to determine the actual type of primitive types (those helpers can be refined as needed), so that it should be possible in most cases, to map the ThingML print to different C print facilities. We should just make sure, or assume, that people will not use things like `print "myVar" + myVar + "\n"`but will use three print statements instead (for which we should be able to determine the type).

**Comment by brice-morin** [comment]
Should now work. A least something like:
```
var myVar : Integer = 0
print "myVar "
print myVar
print "\n"
```

> `print "myVar " + myVar + "\n" is not supported
