### ISSUE TITLE
Globally properties

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#81]
It would be convenient to be able to define global variables where all things use the same "instance" of it.

**Comment by brice-morin** [comment]
OK, we will NOT make some sort of static properties. The only way to thing can exchange information is via asynchronous message passing via ports, not via shared variable. But, in the specific case of the Kevoree compiler, we will try to make something to "merge" all attributes into one e.g. with a @kevoree "global" annotation. Basically the Kevoree attribute will be unique, but the ThingML attributes will remain seperated.

**Comment by brice-morin** [comment]
Actually, I think we have 3 possible mappings:

- @kevoree "instance": this is the current mapping, where we expose all the instances of a ThingML attribute as a separate Kevoree attribute
- @kevoree "merge": where we expose a single Kevoree attribute, which we then sync with all the ThingML instances
- @kevoree "only": where the attribute is just a Kevoree attribute, that the ThingML instances do not really need to know about. Well, not really sure if we need that one right now (since you use the nodeName in the things), but maybe...
